apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-frontend
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-frontend
  template:
    metadata:
      labels:
        app: gateway-frontend
    spec:
      containers:
      - name: gateway-frontend
        image: najwa22/gateway-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: API_URL
          value: "http://objection-app-service:3001"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: session-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: jwt-secret
        - name: ADMIN_PASSWORD_HASH
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: admin-password-hash
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /livez
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe: # Added readiness probe
          httpGet:
            path: /livez
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
