apiVersion: v1
kind: Service
metadata:
  name: gateway-frontend-service
  namespace: crda-namespace
spec:
  selector:
    app: gateway-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
